# Generated by Django 4.2.4 on 2023-08-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sd_support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='author',
        ),
    ]
